### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by Live4dreamCH** [zhang570221322/autoClock#2]
您好!我平时主要写cpp和python, 对js不是很熟悉, 按照您的README指导, 在npm install那一步出现了以下错误, 请问是什么意思, 应该如何解决?

> puppeteer@3.1.0 install /root/autoClock/autoClock/node_modules/puppeteer
> node install.js

ERROR: Failed to set up Chromium r756035! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
Error: EACCES: permission denied, mkdir '/root/autoClock/autoClock/node_modules/puppeteer/.local-chromium'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/root/autoClock/autoClock/node_modules/puppeteer/lib/helper.js:94:19)
    at fetchBinary (/root/autoClock/autoClock/node_modules/puppeteer/install.js:148:8)
    at download (/root/autoClock/autoClock/node_modules/puppeteer/install.js:54:9) {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/root/autoClock/autoClock/node_modules/puppeteer/.local-chromium'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@3.1.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@3.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-19T08_58_24_891Z-debug.log

**Comment by Live4dreamCH** [comment]
另外, 请问是不是允许全过程都在无gui下完成, 我电脑声音比较大, 整天开机舍友觉得吵, 就放在云上了

**Comment by wllzhang** [comment]
> 您好!我平时主要写cpp和python, 对js不是很熟悉, 按照您的README指导, 在npm install那一步出现了以下错误, 请问是什么意思, 应该如何解决?
> 
> > puppeteer@3.1.0 install /root/autoClock/autoClock/node_modules/puppeteer
> > node install.js
> 
> ERROR: Failed to set up Chromium r756035! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
> Error: EACCES: permission denied, mkdir '/root/autoClock/autoClock/node_modules/puppeteer/.local-chromium'
> -- ASYNC --
> at BrowserFetcher. (/root/autoClock/autoClock/node_modules/puppeteer/lib/helper.js:94:19)
> at fetchBinary (/root/autoClock/autoClock/node_modules/puppeteer/install.js:148:8)
> at download (/root/autoClock/autoClock/node_modules/puppeteer/install.js:54:9) {
> errno: -13,
> code: 'EACCES',
> syscall: 'mkdir',
> path: '/root/autoClock/autoClock/node_modules/puppeteer/.local-chromium'
> }
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! puppeteer@3.1.0 install: `node install.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the puppeteer@3.1.0 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /root/.npm/_logs/2020-06-19T08_58_24_891Z-debug.log

你可以尝试 sudo npm install  --unsafe-perm


> 另外, 请问是不是允许全过程都在无gui下完成, 我电脑声音比较大, 整天开机舍友觉得吵, 就放在云上了

可以的，但要设置 noShowUI: true
此外，学校dom会时常变化，我会时常更新。

**Comment by Live4dreamCH** [comment]
抱歉又来打扰您了...在安装好依赖之后运行temp_autoDiDi.js时报错如下

Error: Evaluation failed: TypeError: Cannot read property 'click' of null
    at __puppeteer_evaluation_script__:7:54
    at ExecutionContext._evaluateInternal (/root/autoClock/autoClock/node_modules/puppeteer/lib/ExecutionContext.js:102:19)
    at async ExecutionContext.evaluate (/root/autoClock/autoClock/node_modules/puppeteer/lib/ExecutionContext.js:33:16)
    at async /root/autoClock/autoClock/core/main.js:86:9
  -- ASYNC --
    at ExecutionContext.<anonymous> (/root/autoClock/autoClock/node_modules/puppeteer/lib/helper.js:94:19)
    at DOMWorld.evaluate (/root/autoClock/autoClock/node_modules/puppeteer/lib/DOMWorld.js:89:24)
  -- ASYNC --
    at Frame.<anonymous> (/root/autoClock/autoClock/node_modules/puppeteer/lib/helper.js:94:19)
    at /root/autoClock/autoClock/core/main.js:86:24
然后我把sleep改成了10000还是这样

**Comment by wllzhang** [comment]
这是你打过卡了。你没打卡试试



---原始邮件---
发件人: "Live4dreamCH"<notifications@github.com&gt;
发送时间: 2020年6月20日(周六) 上午8:39
收件人: "zhang570221322/autoClock"<autoClock@noreply.github.com&gt;;
抄送: "zhang570221322"<570221322@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [zhang570221322/autoClock] 安装失败 (#2)




 
抱歉又来打扰您了...在安装好依赖之后运行temp_autoDiDi.js时报错如下
 
Error: Evaluation failed: TypeError: Cannot read property 'click' of null
 at puppeteer_evaluation_script:7:54
 at ExecutionContext._evaluateInternal (/root/autoClock/autoClock/node_modules/puppeteer/lib/ExecutionContext.js:102:19)
 at async ExecutionContext.evaluate (/root/autoClock/autoClock/node_modules/puppeteer/lib/ExecutionContext.js:33:16)
 at async /root/autoClock/autoClock/core/main.js:86:9
 -- ASYNC --
 at ExecutionContext. (/root/autoClock/autoClock/node_modules/puppeteer/lib/helper.js:94:19)
 at DOMWorld.evaluate (/root/autoClock/autoClock/node_modules/puppeteer/lib/DOMWorld.js:89:24)
 -- ASYNC --
 at Frame. (/root/autoClock/autoClock/node_modules/puppeteer/lib/helper.js:94:19)
 at /root/autoClock/autoClock/core/main.js:86:24
 然后我把sleep改成了10000还是这样

**Comment by wllzhang** [comment]
你pull一下



---原始邮件---
发件人: "Live4dreamCH"<notifications@github.com&gt;
发送时间: 2020年6月20日(周六) 上午8:39
收件人: "zhang570221322/autoClock"<autoClock@noreply.github.com&gt;;
抄送: "zhang570221322"<570221322@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [zhang570221322/autoClock] 安装失败 (#2)




 
抱歉又来打扰您了...在安装好依赖之后运行temp_autoDiDi.js时报错如下
 
Error: Evaluation failed: TypeError: Cannot read property 'click' of null
 at puppeteer_evaluation_script:7:54
 at ExecutionContext._evaluateInternal (/root/autoClock/autoClock/node_modules/puppeteer/lib/ExecutionContext.js:102:19)
 at async ExecutionContext.evaluate (/root/autoClock/autoClock/node_modules/puppeteer/lib/ExecutionContext.js:33:16)
 at async /root/autoClock/autoClock/core/main.js:86:9
 -- ASYNC --
 at ExecutionContext. (/root/autoClock/autoClock/node_modules/puppeteer/lib/helper.js:94:19)
 at DOMWorld.evaluate (/root/autoClock/autoClock/node_modules/puppeteer/lib/DOMWorld.js:89:24)
 -- ASYNC --
 at Frame. (/root/autoClock/autoClock/node_modules/puppeteer/lib/helper.js:94:19)
 at /root/autoClock/autoClock/core/main.js:86:24
 然后我把sleep改成了10000还是这样

**Comment by Live4dreamCH** [comment]
> 这是你打过卡了。你没打卡试试
> […](#)
> ---原始邮件--- 发件人: "Live4dreamCH"<notifications@github.com&gt; 发送时间: 2020年6月20日(周六) 上午8:39 收件人: "zhang570221322/autoClock"<autoClock@noreply.github.com&gt;; 抄送: "zhang570221322"<570221322@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题: Re: [zhang570221322/autoClock] 安装失败 (#2) 抱歉又来打扰您了...在安装好依赖之后运行temp_autoDiDi.js时报错如下 Error: Evaluation failed: TypeError: Cannot read property 'click' of null at puppeteer_evaluation_script:7:54 at ExecutionContext._evaluateInternal (/root/autoClock/autoClock/node_modules/puppeteer/lib/ExecutionContext.js:102:19) at async ExecutionContext.evaluate (/root/autoClock/autoClock/node_modules/puppeteer/lib/ExecutionContext.js:33:16) at async /root/autoClock/autoClock/core/main.js:86:9 -- ASYNC -- at ExecutionContext. (/root/autoClock/autoClock/node_modules/puppeteer/lib/helper.js:94:19) at DOMWorld.evaluate (/root/autoClock/autoClock/node_modules/puppeteer/lib/DOMWorld.js:89:24) -- ASYNC -- at Frame. (/root/autoClock/autoClock/node_modules/puppeteer/lib/helper.js:94:19) at /root/autoClock/autoClock/core/main.js:86:24 然后我把sleep改成了10000还是这样 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

啊今早上确实没打过, 并且main.js的更新也已经pull过了

**Comment by zhang570221322** [comment]
你用有UI的界面看一下是哪里出错了。我这边研究生打卡是成功的。

**Comment by wllzhang** [comment]
> > 这是你打过卡了。你没打卡试试
> > […](#)
> > ---原始邮件--- 发件人: "Live4dreamCH"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2020年6月20日(周六) 上午8:39 收件人: "zhang570221322/autoClock"<[autoClock@noreply.github.com](mailto:autoClock@noreply.github.com)>; 抄送: "zhang570221322"<[570221322@qq.com](mailto:570221322@qq.com)>;"Comment"<[comment@noreply.github.com](mailto:comment@noreply.github.com)>; 主题: Re: [zhang570221322/autoClock] 安装失败 (#2) 抱歉又来打扰您了...在安装好依赖之后运行temp_autoDiDi.js时报错如下 Error: Evaluation failed: TypeError: Cannot read property 'click' of null at puppeteer_evaluation_script:7:54 at ExecutionContext._evaluateInternal (/root/autoClock/autoClock/node_modules/puppeteer/lib/ExecutionContext.js:102:19) at async ExecutionContext.evaluate (/root/autoClock/autoClock/node_modules/puppeteer/lib/ExecutionContext.js:33:16) at async /root/autoClock/autoClock/core/main.js:86:9 -- ASYNC -- at ExecutionContext. (/root/autoClock/autoClock/node_modules/puppeteer/lib/helper.js:94:19) at DOMWorld.evaluate (/root/autoClock/autoClock/node_modules/puppeteer/lib/DOMWorld.js:89:24) -- ASYNC -- at Frame. (/root/autoClock/autoClock/node_modules/puppeteer/lib/helper.js:94:19) at /root/autoClock/autoClock/core/main.js:86:24 然后我把sleep改成了10000还是这样 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 啊今早上确实没打过, 并且main.js的更新也已经pull过了

你用有UI的界面看一下是哪里出错了。我这边研究生打卡是成功的。
