### ISSUE TITLE
Tips: Ubuntu server 18.04 上要装下面的库，才能使用 Puppeteer

### ISSUE THREAD

**Issue by xiao2dou** [zhang570221322/autoClock#3]
`sudo apt-get install libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libnss3 libcups2 libxss1 libxrandr2 libasound2 libpangocairo-1.0-0 libatk1.0-0 libatk-bridge2.0-0 libgtk-3-0`

**Comment by wllzhang** [comment]
OK,Thanks
