### ISSUE TITLE
无法执行autoDiDi

### ISSUE THREAD

**Issue by telepathphd** [zhang570221322/autoClock#4]
我的操作是按照Readme来的，然后到最后一步，会一直卡在
`node autoDiDi.js`
前面的temp_autoDiDi是可以执行的。
我把整个文件夹删除了，重新clone了一次，还是这样。

**Comment by wllzhang** [comment]
是正常的。
autoDiDi.js是定时执行，默认是每天早10和16的1分20秒执行，所以不执行的时候就是一直卡着(监控着）。 而temp是立即执行一次打卡。你可以部署在一直开着的电脑上。详情见readme



---原始邮件---
发件人: "telepathphd"<notifications@github.com&gt;
发送时间: 2020年8月7日(周五) 上午9:38
收件人: "zhang570221322/autoClock"<autoClock@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [zhang570221322/autoClock] 无法执行autoDiDi (#4)




 
我的操作是按照Readme来的，然后到最后一步，会一直卡在
 node autoDiDi.js
 前面的temp_autoDiDi是可以执行的。
 我把整个文件夹删除了，重新clone了一次，还是这样。

**Comment by telepathphd** [comment]
这样呀。
我不太清楚这个流程，那如果现在电脑关机一次，需要重新在命令行运行`node autoDiDi.js`吗？
另外，如果我现在想改执行的时间，是：
1.只修改配置文件；
2.修改配置文件后执行`node autoDiDi.js`；
3.需要用某种方法（我不清楚）关闭掉前面执行过的旧js，然后再执行`node autoDiDi.js`；
中的哪一种呢？

**Comment by telepathphd** [comment]
One more thing...
这个多用户怎么删掉一个呢？是把
`  -
    #用户2
    username: xx
    password: xxx
    # 本科生 || 研究生
    type: 研究生               
    # 到过校园
    # 创新港校区 || 兴庆校区 || 雁塔校区 || 曲江校区
    campus: 创新港校区
    # 接受打卡成功反馈的邮箱
    revMail: xxxxxxxxx@qq.com`
全部注释吗？还是说那个"  - "得留着？

**Comment by wllzhang** [comment]
1 执行了 node autodidi.js相当于运行了一个程序。重启会关闭这个程序。
2 修改执行时间前后如果程序运行，关闭掉前面执行过的旧js，然后再执行node autoDiDi.js
3 关闭程序的方法跟操作系统有关，win是任务管理器，linux是kill -9

---原始邮件---
发件人: "telepathphd"<notifications@github.com&gt;
发送时间: 2020年8月7日(周五) 中午12:56
收件人: "zhang570221322/autoClock"<autoClock@noreply.github.com&gt;;
抄送: "cszhang"<570221322@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [zhang570221322/autoClock] 无法执行autoDiDi (#4)




 
这样呀。
 我不太清楚这个流程，那如果现在电脑关机一次，需要重新在命令行运行node autoDiDi.js吗？
 另外，如果我现在想改执行的时间，是：
 1.只修改配置文件；
 2.修改配置文件后执行node autoDiDi.js；
 3.需要用某种方法（我不清楚）关闭掉前面执行过的旧js，然后再执行node autoDiDi.js；
 中的哪一种呢？

**Comment by telepathphd** [comment]
> 是正常的。 autoDiDi.js是定时执行，默认是每天早10和16的1分20秒执行，所以不执行的时候就是一直卡着(监控着）。 而temp是立即执行一次打卡。你可以部署在一直开着的电脑上。详情见readme

刚刚想到一个建议哈，可以在运行autoDiDi时大概输出一下在做什么，或者说正在执行，不然看起来就像哪里没安装好的样子。

**Comment by wllzhang** [comment]
–也删掉。



---原始邮件---
发件人: "telepathphd"<notifications@github.com&gt;
发送时间: 2020年8月7日(周五) 中午12:59
收件人: "zhang570221322/autoClock"<autoClock@noreply.github.com&gt;;
抄送: "cszhang"<570221322@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [zhang570221322/autoClock] 无法执行autoDiDi (#4)




 
One more thing...
 这个多用户怎么删掉一个呢？是把
   - #用户2 username: xx password: xxx # 本科生 || 研究生 type: 研究生                # 到过校园 # 创新港校区 || 兴庆校区 || 雁塔校区 || 曲江校区 campus: 创新港校区 # 接受打卡成功反馈的邮箱 revMail: xxxxxxxxx@qq.com
 全部注释吗？还是说那个"  - "得留着？

**Comment by wllzhang** [comment]
好的。感谢提议。



---原始邮件---
发件人: "telepathphd"<notifications@github.com&gt;
发送时间: 2020年8月7日(周五) 中午1:05
收件人: "zhang570221322/autoClock"<autoClock@noreply.github.com&gt;;
抄送: "cszhang"<570221322@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [zhang570221322/autoClock] 无法执行autoDiDi (#4)




  
是正常的。 autoDiDi.js是定时执行，默认是每天早10和16的1分20秒执行，所以不执行的时候就是一直卡着(监控着）。 而temp是立即执行一次打卡。你可以部署在一直开着的电脑上。详情见readme
  
刚刚想到一个建议哈，可以在运行autoDiDi时大概输出一下在做什么，或者说正在执行，不然看起来就像哪里没安装好的样子。
