### ISSUE TITLE
TypeError: Cannot read property 'waitForSelector' of undefined

### ISSUE THREAD

**Issue by nbwin** [zhang570221322/autoClock#8]
你好，在ubuntu 20.04 lts 上使用报错
TypeError: Cannot read property 'waitForSelector' of undefined
    at my_main (/home/pt/autoClock/core/main.js:53:28)
    at async /home/pt/autoClock/core/main.js:172:18

（而且readme中node temp_autoDiDi.js 的描述应该是 node autoDiDi_Once.js ，应该是忘记更新了）

**Comment by wllzhang** [comment]
主要是利用这一网站填报：http://jkrb.xjtu.edu.cn/EIP/user/index.htm
这个报错具体是找不到这个：
![Uploading image.png…]()

**Comment by nbwin** [comment]
> 主要是利用这一网站填报：http://jkrb.xjtu.edu.cn/EIP/user/index.htm
> 这个报错具体是找不到这个：

你好，图片挂了哈哈

**Comment by wllzhang** [comment]
链接: https://pan.baidu.com/s/1dEkINYSwjnKMdcE4Hb6guA 提取码: 72jc 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by nbwin** [comment]
> 链接: https://pan.baidu.com/s/1dEkINYSwjnKMdcE4Hb6guA 提取码: 72jc 复制这段内容后打开百度网盘手机App，操作更方便哦

啊这，有没有解决方法呢QAQ

**Comment by wllzhang** [comment]
你重新装下试试把， 我这边一直在用都没问题

**Comment by nbwin** [comment]
> 你重新装下试试把， 我这边一直在用都没问题

好的，我试试

**Comment by wllzhang** [comment]
有可能是网速太慢了，DOM没来及加载，你修改一下配置文件的
# 每次操作间隔时间,依据网速来定.默认5000毫秒,电脑网速过慢可以增加.
  interval: 5000

**Comment by xiaoguoyi** [comment]
我用win的试了试，发现进入这个页面后会重新回到填netid 和密码的页面
![image](https://user-images.githubusercontent.com/54239687/99561504-fcd3b980-2a01-11eb-990e-73120d53472f.png)

**Comment by nbwin** [comment]
用win的ui试了试，发现进入**健康每日报**（就是第二次填账号密码那个地方）的 认证 填不上账号密码，就会进行下一次填报，操作间隔已设置成10000
![image](https://user-images.githubusercontent.com/54239687/99563188-f9413200-2a03-11eb-9965-be0dfb481f01.png)

**Comment by wllzhang** [comment]
OK, 逻辑变了,我改改

**Comment by wllzhang** [comment]
已经更新
